interface GitHubScanResult {
  repository: string;
  branch: string;
  totalFiles: number;
  scannedFiles: number;
  totalIssues: number;
  files: Array<{
    path: string;
    language: string;
    issues: Array<{
      line: number;
      type: string;
      severity: 'error' | 'warning' | 'info';
      message: string;
      original: string;
      fixed?: string;
      description?: string;
    }>;
  }>;
  summary: {
    errors: number;
    warnings: number;
    suggestions: number;
  };
  structureSuggestions?: string[];
}

export const generateTextSummary = (
  result: GitHubScanResult,
  timestamp: string,
  issuesByType: Map<string, number>,
  issuesBySeverity: { errors: number; warnings: number; info: number },
  fixesApplied: boolean
) => {
  return `
╔════════════════════════════════════════════════════════════════════╗
║                     AI CODE ASSISTANT                              ║
║                   ERROR SUMMARY REPORT                             ║
╚════════════════════════════════════════════════════════════════════╝

Repository: ${result.repository}
Branch: ${result.branch}
Scan Date: ${timestamp}
Total Files Scanned: ${result.scannedFiles}
Total Issues Found: ${result.totalIssues}

═══════════════════════════════════════════════════════════════════
                        SEVERITY BREAKDOWN
═══════════════════════════════════════════════════════════════════

❌ Errors:      ${issuesBySeverity.errors}
⚠️  Warnings:    ${issuesBySeverity.warnings}
💡 Suggestions: ${issuesBySeverity.info}

═══════════════════════════════════════════════════════════════════
                        ISSUE TYPE BREAKDOWN
═══════════════════════════════════════════════════════════════════

${Array.from(issuesByType.entries())
  .sort((a, b) => b[1] - a[1])
  .map(([type, count]) => `• ${type.padEnd(30)} ${count}`)
  .join('\n')}

${result.structureSuggestions && result.structureSuggestions.length > 0 ? `
═══════════════════════════════════════════════════════════════════
                   DIRECTORY STRUCTURE SUGGESTIONS
═══════════════════════════════════════════════════════════════════

${result.structureSuggestions.map(s => `• ${s}`).join('\n')}
` : ''}

═══════════════════════════════════════════════════════════════════
                        DETAILED ISSUES BY FILE
═══════════════════════════════════════════════════════════════════

${result.files
  .filter(f => f.issues.length > 0)
  .map(file => `
┌─────────────────────────────────────────────────────────────────┐
│ FILE: ${file.path.padEnd(58)}│
│ LANGUAGE: ${file.language.padEnd(54)}│
│ ISSUES: ${String(file.issues.length).padEnd(56)}│
└─────────────────────────────────────────────────────────────────┘

${file.issues.map((issue, idx) => `
  [${idx + 1}] Line ${issue.line}: ${issue.message}
  ─────────────────────────────────────────────────────────────
  Type: ${issue.type}
  Severity: ${issue.severity.toUpperCase()}
  
  ❌ BEFORE:
  ${issue.original}
  
  ${issue.fixed ? `✅ AFTER:\n  ${issue.fixed}\n` : ''}
  💡 EXPLANATION:
  ${issue.description || 'No additional details.'}
  
`).join('\n')}
`).join('\n')}

═══════════════════════════════════════════════════════════════════
                           CLEAN FILES
═══════════════════════════════════════════════════════════════════

${result.files
  .filter(f => f.issues.length === 0)
  .map(f => `✅ ${f.path}`)
  .join('\n') || 'No clean files found.'}

═══════════════════════════════════════════════════════════════════
                              SUMMARY
═══════════════════════════════════════════════════════════════════

Files with Issues: ${result.files.filter(f => f.issues.length > 0).length}
Clean Files: ${result.files.filter(f => f.issues.length === 0).length}
Total Files: ${result.scannedFiles}
Success Rate: ${Math.round((result.files.filter(f => f.issues.length === 0).length / result.scannedFiles) * 100)}%

${fixesApplied ? '✅ All fixes have been applied!' : '⚠️  Run "Fix All Issues" to apply automatic corrections.'}

═══════════════════════════════════════════════════════════════════
Generated by AI Code Assistant - ${timestamp}
═══════════════════════════════════════════════════════════════════
`.trim();
};

export const generateJSONSummary = (
  result: GitHubScanResult,
  timestamp: string,
  issuesByType: Map<string, number>,
  issuesBySeverity: { errors: number; warnings: number; info: number },
  fixesApplied: boolean
) => {
  const jsonReport = {
    metadata: {
      repository: result.repository,
      branch: result.branch,
      scanDate: timestamp,
      totalFiles: result.scannedFiles,
      totalIssues: result.totalIssues,
      fixesApplied
    },
    summary: {
      severity: issuesBySeverity,
      issueTypes: Object.fromEntries(issuesByType),
      filesWithIssues: result.files.filter(f => f.issues.length > 0).length,
      cleanFiles: result.files.filter(f => f.issues.length === 0).length,
      successRate: Math.round((result.files.filter(f => f.issues.length === 0).length / result.scannedFiles) * 100)
    },
    structureSuggestions: result.structureSuggestions || [],
    files: result.files.map(file => ({
      path: file.path,
      language: file.language,
      issueCount: file.issues.length,
      issues: file.issues.map(issue => ({
        line: issue.line,
        type: issue.type,
        severity: issue.severity,
        message: issue.message,
        original: issue.original,
        fixed: issue.fixed,
        description: issue.description
      }))
    }))
  };
  return JSON.stringify(jsonReport, null, 2);
};

export const generateHTMLSummary = (
  result: GitHubScanResult,
  timestamp: string,
  issuesByType: Map<string, number>,
  issuesBySeverity: { errors: number; warnings: number; info: number },
  fixesApplied: boolean
) => {
  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Error Summary - ${result.repository}</title>
  <style>
    * { margin: 0; padding: 0; box-sizing: border-box; }
    body {
      font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', 'Roboto', sans-serif;
      background: linear-gradient(135deg, #1a1a2e 0%, #16213e 100%);
      color: #e0e0e0;
      padding: 20px;
      line-height: 1.6;
    }
    .container { max-width: 1200px; margin: 0 auto; background: #0f0f1e; border-radius: 12px; padding: 30px; box-shadow: 0 10px 40px rgba(0,0,0,0.5); }
    h1 { color: #4ade80; font-size: 2.5em; margin-bottom: 10px; text-align: center; }
    h2 { color: #60a5fa; margin: 30px 0 15px; padding-bottom: 10px; border-bottom: 2px solid #374151; }
    .header { text-align: center; margin-bottom: 40px; padding: 20px; background: linear-gradient(135deg, #065f46 0%, #047857 100%); border-radius: 8px; }
    .stats { display: grid; grid-template-columns: repeat(auto-fit, minmax(200px, 1fr)); gap: 15px; margin: 20px 0; }
    .stat-card { background: #1f2937; padding: 20px; border-radius: 8px; text-align: center; border-left: 4px solid #4ade80; }
    .stat-card.error { border-left-color: #ef4444; }
    .stat-card.warning { border-left-color: #f59e0b; }
    .stat-card.info { border-left-color: #3b82f6; }
    .stat-value { font-size: 2.5em; font-weight: bold; color: #4ade80; }
    .stat-label { color: #9ca3af; font-size: 0.9em; margin-top: 5px; }
    .issue-types { background: #1f2937; padding: 20px; border-radius: 8px; margin: 20px 0; }
    .issue-type-item { display: flex; justify-content: space-between; padding: 10px; border-bottom: 1px solid #374151; }
    .issue-type-item:last-child { border-bottom: none; }
    .file-card { background: #1f2937; margin: 15px 0; border-radius: 8px; overflow: hidden; border: 1px solid #374151; }
    .file-header { background: #374151; padding: 15px; display: flex; justify-content: space-between; align-items: center; }
    .file-path { color: #4ade80; font-weight: 600; }
    .issue-badge { background: #ef4444; color: white; padding: 4px 12px; border-radius: 12px; font-size: 0.85em; font-weight: bold; }
    .issue { background: #0f0f1e; margin: 10px; padding: 15px; border-left: 3px solid #ef4444; border-radius: 4px; }
    .issue.warning { border-left-color: #f59e0b; }
    .issue.info { border-left-color: #3b82f6; }
    .issue-type { background: #374151; padding: 4px 10px; border-radius: 4px; font-size: 0.85em; }
    .code-block { background: #000; padding: 12px; border-radius: 4px; margin: 10px 0; overflow-x: auto; font-family: 'Courier New', monospace; font-size: 0.9em; }
    .code-before { border-left: 3px solid #ef4444; }
    .code-after { border-left: 3px solid #4ade80; }
    .code-label { color: #9ca3af; font-size: 0.8em; margin-bottom: 5px; }
    .description { background: #1f2937; padding: 12px; border-radius: 4px; margin-top: 10px; color: #60a5fa; font-size: 0.9em; }
    .clean-files { background: #065f46; padding: 20px; border-radius: 8px; margin: 20px 0; }
    .clean-file { color: #4ade80; padding: 5px 0; }
    .footer { text-align: center; margin-top: 40px; padding-top: 20px; border-top: 1px solid #374151; color: #6b7280; font-size: 0.9em; }
    .suggestions { background: #581c87; padding: 20px; border-radius: 8px; margin: 20px 0; border: 1px solid #7c3aed; }
    .suggestion-item { color: #c084fc; padding: 8px 0; }
  </style>
</head>
<body>
  <div class="container">
    <div class="header">
      <h1>🔍 AI Code Assistant</h1>
      <h2 style="color: white; border: none; margin: 10px 0;">Error Summary Report</h2>
      <p style="color: #d1fae5; margin-top: 10px;">Repository: ${result.repository} • Branch: ${result.branch}</p>
      <p style="color: #d1fae5; font-size: 0.9em;">Generated: ${timestamp}</p>
    </div>

    <div class="stats">
      <div class="stat-card">
        <div class="stat-value">${result.scannedFiles}</div>
        <div class="stat-label">Files Scanned</div>
      </div>
      <div class="stat-card error">
        <div class="stat-value" style="color: #ef4444;">${result.totalIssues}</div>
        <div class="stat-label">Total Issues</div>
      </div>
      <div class="stat-card error">
        <div class="stat-value" style="color: #ef4444;">${issuesBySeverity.errors}</div>
        <div class="stat-label">Errors</div>
      </div>
      <div class="stat-card warning">
        <div class="stat-value" style="color: #f59e0b;">${issuesBySeverity.warnings}</div>
        <div class="stat-label">Warnings</div>
      </div>
      <div class="stat-card info">
        <div class="stat-value" style="color: #3b82f6;">${issuesBySeverity.info}</div>
        <div class="stat-label">Suggestions</div>
      </div>
    </div>

    <h2>📊 Issue Type Breakdown</h2>
    <div class="issue-types">
      ${Array.from(issuesByType.entries())
        .sort((a, b) => b[1] - a[1])
        .map(([type, count]) => `
          <div class="issue-type-item">
            <span style="text-transform: capitalize;">${type}</span>
            <span style="color: #4ade80; font-weight: bold;">${count}</span>
          </div>
        `).join('')}
    </div>

    ${result.structureSuggestions && result.structureSuggestions.length > 0 ? `
      <h2>📁 Directory Structure Suggestions</h2>
      <div class="suggestions">
        ${result.structureSuggestions.map(s => `<div class="suggestion-item">• ${s}</div>`).join('')}
      </div>
    ` : ''}

    <h2>📝 Detailed Issues by File</h2>
    ${result.files
      .filter(f => f.issues.length > 0)
      .map(file => `
        <div class="file-card">
          <div class="file-header">
            <div>
              <div class="file-path">${file.path}</div>
              <div style="color: #9ca3af; font-size: 0.85em; margin-top: 4px;">Language: ${file.language}</div>
            </div>
            <div class="issue-badge">${file.issues.length} issue${file.issues.length !== 1 ? 's' : ''}</div>
          </div>
          <div style="padding: 15px;">
            ${file.issues.map(issue => `
              <div class="issue ${issue.severity}">
                <div style="display: flex; justify-content: space-between; margin-bottom: 10px;">
                  <div>
                    <strong>Line ${issue.line}:</strong> ${issue.message}
                  </div>
                  <div class="issue-type">${issue.type} • ${issue.severity.toUpperCase()}</div>
                </div>
                
                <div class="code-label">❌ Before:</div>
                <div class="code-block code-before"><code>${issue.original.replace(/</g, '&lt;').replace(/>/g, '&gt;')}</code></div>
                
                ${issue.fixed ? `
                  <div class="code-label">✅ After:</div>
                  <div class="code-block code-after"><code>${issue.fixed.replace(/</g, '&lt;').replace(/>/g, '&gt;')}</code></div>
                ` : ''}
                
                ${issue.description ? `
                  <div class="description">
                    <strong>💡 Explanation:</strong> ${issue.description}
                  </div>
                ` : ''}
              </div>
            `).join('')}
          </div>
        </div>
      `).join('')}

    ${result.files.filter(f => f.issues.length === 0).length > 0 ? `
      <h2>✅ Clean Files (No Issues)</h2>
      <div class="clean-files">
        ${result.files
          .filter(f => f.issues.length === 0)
          .map(f => `<div class="clean-file">✓ ${f.path}</div>`)
          .join('')}
      </div>
    ` : ''}

    <div class="footer">
      <p><strong>Summary:</strong> ${result.files.filter(f => f.issues.length > 0).length} files with issues • ${result.files.filter(f => f.issues.length === 0).length} clean files • ${Math.round((result.files.filter(f => f.issues.length === 0).length / result.scannedFiles) * 100)}% success rate</p>
      <p style="margin-top: 10px;">${fixesApplied ? '✅ All fixes have been applied!' : '⚠️ Run "Fix All Issues" to apply automatic corrections.'}</p>
      <p style="margin-top: 15px;">Generated by AI Code Assistant • ${timestamp}</p>
    </div>
  </div>
</body>
</html>`;
};
