// =============================================================================
// EXPORT FORMATS — PDF, DOCX, Markdown Export
// =============================================================================

import type { BlogPost } from './blogGenerator';

// =============================================================================
// MARKDOWN EXPORT
// =============================================================================

export function exportToMarkdown(posts: BlogPost[]): string {
  const markdown = posts.map(post => {
    const frontmatter = `---
title: ${post.seoTitle || 'Untitled'}
duration: ${post.duration}s
quality-score: ${post.qualityScore || 'N/A'}
word-count: ${post.wordCount || 0}
primary-keyword: ${post.primaryKeyword || 'N/A'}
secondary-keywords: ${(post.secondaryKeywords || []).join(', ')}
character: ${post.character?.name || 'N/A'}
date: ${new Date(post.timestamp).toISOString()}
---

`;

    const content = `# ${post.seoTitle || 'Untitled Blog Post'}

${post.metaDescription ? `> ${post.metaDescription}\n\n` : ''}${post.content}

---

**Metadata:**
- Duration: ${post.duration} seconds
- Quality Score: ${post.qualityScore || 'N/A'}
- Word Count: ${post.wordCount || 0}
- Primary Keyword: ${post.primaryKeyword || 'N/A'}
${post.secondaryKeywords && post.secondaryKeywords.length > 0 ? `- Secondary Keywords: ${post.secondaryKeywords.join(', ')}\n` : ''}${post.character ? `- Character: ${post.character.name}\n` : ''}
`;

    return frontmatter + content;
  }).join('\n\n---\n\n');

  return markdown;
}

export function downloadMarkdown(posts: BlogPost[], filename?: string): void {
  const markdown = exportToMarkdown(posts);
  const blob = new Blob([markdown], { type: 'text/markdown' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename || `blog-posts-${Date.now()}.md`;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

// =============================================================================
// HTML EXPORT (for PDF conversion)
// =============================================================================

export function exportToHTML(posts: BlogPost[]): string {
  const html = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Blog Posts Export</title>
  <style>
    body {
      font-family: 'Georgia', serif;
      line-height: 1.6;
      max-width: 800px;
      margin: 0 auto;
      padding: 40px 20px;
      color: #333;
    }
    h1 {
      color: #2c3e50;
      border-bottom: 3px solid #3498db;
      padding-bottom: 10px;
      margin-top: 40px;
    }
    h2 {
      color: #34495e;
      margin-top: 30px;
    }
    .meta {
      background: #ecf0f1;
      padding: 15px;
      border-left: 4px solid #3498db;
      margin: 20px 0;
      font-size: 0.9em;
    }
    .meta strong {
      color: #2c3e50;
    }
    .content {
      margin: 20px 0;
      white-space: pre-wrap;
    }
    .post {
      margin-bottom: 60px;
      page-break-after: always;
    }
    .post:last-child {
      page-break-after: auto;
    }
    blockquote {
      border-left: 4px solid #95a5a6;
      padding-left: 20px;
      margin: 20px 0;
      font-style: italic;
      color: #7f8c8d;
    }
  </style>
</head>
<body>
  <h1>Blog Posts Collection</h1>
  <p>Exported on ${new Date().toLocaleDateString()} at ${new Date().toLocaleTimeString()}</p>
  <p>Total Posts: ${posts.length}</p>
  <hr>

  ${posts.map((post, index) => `
  <div class="post">
    <h2>${index + 1}. ${post.seoTitle || 'Untitled Blog Post'}</h2>

    ${post.metaDescription ? `<blockquote>${post.metaDescription}</blockquote>` : ''}

    <div class="meta">
      <p><strong>Duration:</strong> ${post.duration} seconds</p>
      <p><strong>Quality Score:</strong> ${post.qualityScore || 'N/A'}</p>
      <p><strong>Word Count:</strong> ${post.wordCount || 0}</p>
      <p><strong>Primary Keyword:</strong> ${post.primaryKeyword || 'N/A'}</p>
      ${post.secondaryKeywords && post.secondaryKeywords.length > 0 ? `<p><strong>Secondary Keywords:</strong> ${post.secondaryKeywords.join(', ')}</p>` : ''}
      ${post.character ? `<p><strong>Character:</strong> ${post.character.name}</p>` : ''}
      <p><strong>Date:</strong> ${new Date(post.timestamp).toLocaleString()}</p>
    </div>

    <div class="content">${post.content}</div>
  </div>
  `).join('\n')}

  <footer style="margin-top: 60px; padding-top: 20px; border-top: 2px solid #ecf0f1; text-align: center; color: #95a5a6; font-size: 0.9em;">
    <p>Generated by Trending Blog Master</p>
  </footer>
</body>
</html>`;

  return html;
}

export function downloadHTML(posts: BlogPost[], filename?: string): void {
  const html = exportToHTML(posts);
  const blob = new Blob([html], { type: 'text/html' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename || `blog-posts-${Date.now()}.html`;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

// =============================================================================
// PDF EXPORT (using browser print)
// =============================================================================

export function exportToPDF(posts: BlogPost[]): void {
  const html = exportToHTML(posts);

  // Open HTML in new window and trigger print dialog
  const printWindow = window.open('', '_blank');
  if (!printWindow) {
    alert('Please allow popups to export as PDF');
    return;
  }

  printWindow.document.write(html);
  printWindow.document.close();

  // Wait for content to load, then print
  printWindow.onload = () => {
    printWindow.print();
  };
}

// =============================================================================
// PLAIN TEXT EXPORT
// =============================================================================

export function exportToText(posts: BlogPost[]): string {
  const text = posts.map((post, index) => {
    const header = `${'='.repeat(80)}
POST ${index + 1}: ${post.seoTitle || 'Untitled Blog Post'}
${'='.repeat(80)}

`;

    const meta = `METADATA:
  Duration: ${post.duration} seconds
  Quality Score: ${post.qualityScore || 'N/A'}
  Word Count: ${post.wordCount || 0}
  Primary Keyword: ${post.primaryKeyword || 'N/A'}
  ${post.secondaryKeywords && post.secondaryKeywords.length > 0 ? `Secondary Keywords: ${post.secondaryKeywords.join(', ')}\n  ` : ''}${post.character ? `Character: ${post.character.name}\n  ` : ''}Date: ${new Date(post.timestamp).toLocaleString()}

`;

    const description = post.metaDescription ? `DESCRIPTION:\n  ${post.metaDescription}\n\n` : '';

    const content = `CONTENT:\n${post.content}\n\n`;

    return header + meta + description + content;
  }).join('\n');

  return text;
}

export function downloadText(posts: BlogPost[], filename?: string): void {
  const text = exportToText(posts);
  const blob = new Blob([text], { type: 'text/plain' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename || `blog-posts-${Date.now()}.txt`;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

// =============================================================================
// JSON EXPORT (structured data)
// =============================================================================

export function exportToJSON(posts: BlogPost[]): string {
  const exportData = posts.map(post => ({
    title: post.seoTitle || 'Untitled',
    content: post.content,
    duration: post.duration,
    qualityScore: post.qualityScore,
    wordCount: post.wordCount,
    seoTitle: post.seoTitle,
    metaDescription: post.metaDescription,
    slug: post.slug,
    primaryKeyword: post.primaryKeyword,
    secondaryKeywords: post.secondaryKeywords || [],
    character: post.character?.name,
    timestamp: post.timestamp,
    angle: post.angle,
    angleLabel: post.angleLabel,
  }));

  return JSON.stringify(exportData, null, 2);
}

export function downloadJSON(posts: BlogPost[], filename?: string): void {
  const json = exportToJSON(posts);
  const blob = new Blob([json], { type: 'application/json' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename || `blog-posts-${Date.now()}.json`;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

// =============================================================================
// CSV EXPORT (spreadsheet compatible)
// =============================================================================

export function exportToCSV(posts: BlogPost[]): string {
  const headers = [
    'Title',
    'Content',
    'Duration (s)',
    'Quality Score',
    'Word Count',
    'Meta Description',
    'Slug',
    'Primary Keyword',
    'Secondary Keywords',
    'Character',
    'Date',
    'Angle',
  ].join(',');

  const escapeCSV = (value: any): string => {
    if (value === null || value === undefined) return '';
    const str = String(value);
    // Escape quotes and wrap in quotes if contains comma, quote, or newline
    if (str.includes(',') || str.includes('"') || str.includes('\n')) {
      return `"${str.replace(/"/g, '""')}"`;
    }
    return str;
  };

  const rows = posts.map(post => [
    escapeCSV(post.seoTitle || 'Untitled'),
    escapeCSV(post.content),
    escapeCSV(post.duration),
    escapeCSV(post.qualityScore || ''),
    escapeCSV(post.wordCount || ''),
    escapeCSV(post.metaDescription || ''),
    escapeCSV(post.slug || ''),
    escapeCSV(post.primaryKeyword || ''),
    escapeCSV((post.secondaryKeywords || []).join('; ')),
    escapeCSV(post.character?.name || ''),
    escapeCSV(new Date(post.timestamp).toISOString()),
    escapeCSV(post.angleLabel || ''),
  ].join(','));

  return [headers, ...rows].join('\n');
}

export function downloadCSV(posts: BlogPost[], filename?: string): void {
  const csv = exportToCSV(posts);
  const blob = new Blob([csv], { type: 'text/csv' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename || `blog-posts-${Date.now()}.csv`;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}
