// Git Repair ZIP Generator
// Generates downloadable ZIP files with all fixed and new files

import JSZip from 'jszip';

export async function generateProjectZip(
  fixedFiles: Map<string, string>,
  newFiles: Map<string, string>,
  projectName: string
): Promise<void> {
  const zip = new JSZip();
  
  // Add fixed files
  fixedFiles.forEach((content, filePath) => {
    // Remove leading slash if present
    const cleanPath = filePath.startsWith('/') ? filePath.slice(1) : filePath;
    zip.file(cleanPath, content);
  });
  
  // Add new files
  newFiles.forEach((content, filePath) => {
    const cleanPath = filePath.startsWith('/') ? filePath.slice(1) : filePath;
    zip.file(cleanPath, content);
  });
  
  // Add README with repair summary
  const readme = generateReadme(fixedFiles, newFiles);
  zip.file('GIT_REPAIR_SUMMARY.md', readme);
  
  // Generate ZIP blob
  const blob = await zip.generateAsync({ type: 'blob' });
  
  // Create download link
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = `${projectName}-repaired-${Date.now()}.zip`;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

function generateReadme(fixedFiles: Map<string, string>, newFiles: Map<string, string>): string {
  return `# Git Repair - Repaired Project

**Generated:** ${new Date().toLocaleString()}

---

## 📦 Package Contents

This ZIP file contains all files that have been repaired or created by the Git Repair AI system.

### ✅ Fixed Files (${fixedFiles.size})

${Array.from(fixedFiles.keys()).map((file, i) => `${i + 1}. \`${file}\``).join('\n')}

${newFiles.size > 0 ? `
### ✨ New Files Created (${newFiles.size})

${Array.from(newFiles.keys()).map((file, i) => `${i + 1}. \`${file}\``).join('\n')}
` : ''}

---

## 🚀 Next Steps

1. **Extract this ZIP** to your project directory
2. **Review the changes** in each fixed file
3. **Run your build**: \`npm run dev\`
4. **Test thoroughly** before deploying

---

## 🧠 Repair Information

- **System:** Git Repair - Self-Healing Build System
- **AI Agents:** 12-Agent Autonomous Brain
- **Total Files:** ${fixedFiles.size + newFiles.size}
- **Repair Date:** ${new Date().toLocaleDateString()}

---

_Generated by Git Repair AI - Autonomous Code Repair System_
`;
}

// Generate individual file with missing dependencies
export function generateMissingFile(fileName: string, dependencies: string[]): string {
  const ext = fileName.split('.').pop()?.toLowerCase();
  
  if (ext === 'tsx' || ext === 'jsx') {
    return `import React from 'react';

// Auto-generated by Git Repair
// This file was missing and has been created to resolve dependencies

${dependencies.map(dep => `// Required by: ${dep}`).join('\n')}

export default function ${fileName.split('/').pop()?.replace(/\.(tsx|jsx)$/, '')}() {
  return (
    <div>
      <h1>Auto-Generated Component</h1>
      <p>This component was created by Git Repair to resolve missing dependencies.</p>
    </div>
  );
}
`;
  } else if (ext === 'ts' || ext === 'js') {
    return `// Auto-generated by Git Repair
// This file was missing and has been created to resolve dependencies

${dependencies.map(dep => `// Required by: ${dep}`).join('\n')}

export function placeholder() {
  return 'This is an auto-generated placeholder function';
}

export default {};
`;
  } else if (ext === 'css') {
    return `/* Auto-generated by Git Repair */
/* This file was missing and has been created to resolve dependencies */

${dependencies.map(dep => `/* Required by: ${dep} */`).join('\n')}

.container {
  /* Add your styles here */
}
`;
  }
  
  return `// Auto-generated by Git Repair
// This file was missing and has been created to resolve dependencies

${dependencies.map(dep => `// Required by: ${dep}`).join('\n')}
`;
}